### ISSUE TITLE
Uncaught ReferenceError: StackBlur is not defined

### ISSUE THREAD

**Issue by wunzer0** [flozz/StackBlur#32]
I'm new to JS. Can someone guide me? I want to add StackBlur to the entire canvas but I don't know how.

I added the script (`<script src="assets/js/stackblur.js"></script>`) to my HTML and (`StackBlur.canvasRGBA(targetCanvas, 0, 0, 800, 600, 50);
 `) to my JS. 

How do I make it work?

**Comment by brettz9** [comment]
You need the copy of `stackblur.js` (or `stackblur.min.js`) in the `dist` folder.

Closing as that should resolve, but feel free to comment further.

**Comment by wunzer0** [comment]
Thanks! I was using the wrong file. I have another error now: 

`targetCanvas is not defined`. When I change targetCanvas to canvas, the error disappears but there's no blur. 

My Stackblur code: `StackBlur.canvasRGBA(targetCanvas, 0, 0, 800, 600, 50);`
My canvas: `<canvas id="canvas" width="800" height="600"></canvas>`

**Comment by brettz9** [comment]
`targetCanvas` means, as per the README, "the `HTMLCanvasElement` or its `id`."; it is not a reference to an actual global variable. The reason `canvas` works is because you have an ID "canvas" and HTML exposes these as globals. But it is not considered good practice to rely on this. It is better to use `document.getElementById` or `document.querySelector` to find your canvas element and then you can supply it to `canvasRGBA`.

You also have to have something drawn on the canvas.

I suggest your taking a look at the demo file and working with that.

For further support questions, you can use a site like https://stackoverflow.com .
